services:
  redis:
    image: redis:7-alpine
    container_name: morningstar_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - morningstar_network

  # Unified AI Services с Celery Worker
  ai_services:
    build:
      context: ./ai_services
      dockerfile: Dockerfile
    container_name: morningstar_ai_services
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_WORKER_LOGLEVEL=INFO
      - CELERY_WORKER_CONCURRENCY=4
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BACKEND_API_URL=http://host.docker.internal:8000
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./ai_services:/app
      - ./ai_services/logs:/app/logs
    networks:
      - morningstar_network

  # Flower dashboard для мониторинга Celery
  flower:
    image: mher/flower:2.0
    container_name: morningstar_flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
      - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH:-admin:admin}
    depends_on:
      redis:
        condition: service_healthy
      ai_services:
        condition: service_started
    restart: unless-stopped
    networks:
      - morningstar_network

volumes:
  redis_data:
    driver: local

networks:
  morningstar_network:
    driver: bridge